openapi: 3.0.1
info:
  title: test-api
  description: ''
  version: '1.0'
servers:
  - url: https://apim-hs0416-dev.azure-api.net/testapi
paths:
  /test:
    get:
      summary: test
      operationId: test
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]